version: 0.2

env:
    variables:
      TF_VERSION: "0.12.9"
      ASSUME_ROLE_ARN: "arn:aws:iam::284744337008:role/mgcp-test-codebuild-deployment-role"
      ENV_TYPE_ASSUME: "mgcp-test"
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      # install required binary
      - "curl -s -qL -o /usr/bin/jq https://stedolan.github.io/jq/download/linux64/jq"
      - "chmod +x /usr/bin/jq"
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      # - "mv terraform /usr/bin"
    
  pre_build:
    commands:
      # Workaround until TF supports creds via Task Roles when running on ECS or CodeBuild
      # See: https://github.com/hashicorp/terraform/issues/8746
      - aws sts get-caller-identity
      - aws_credentials=$(aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name $ENV_TYPE_ASSUME)
      - export AWS_ACCESS_KEY_ID=$(echo "$aws_credentials" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "$aws_credentials" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "$aws_credentials" | jq -r '.Credentials.SessionToken')
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - ls -al
      - terraform --version
      #- cd "environments/$TF_ENV/"

      # - terraform $TF_ACTION -no-color
      - aws sts get-caller-identity
      - cd infra/terraform/providers/aws/us_east_1_test
      - terraform init -no-color
      #- terraform apply -no-color
  post_build:
    commands:
      - echo "terraform $TF_ACTION completed on `date`"
artifacts:
  files:
    - '**/*'