version: 0.2

env:
    variables:
      TF_VERSION: "0.12.9"
      ASSUME_ROLE_ARN: "arn:aws:iam::421923624608:role/mgcp-codebuild"
      ENV_TYPE_ASSUME: "mgcp-test"
phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      # install required binary
      - "yum -y install jq"
      - "cd /usr/bin"
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      # - "mv terraform /usr/bin"
    
  pre_build:
    commands:
      # Workaround until TF supports creds via Task Roles when running on ECS or CodeBuild
      # See: https://github.com/hashicorp/terraform/issues/8746
      - aws sts get-caller-identity
      - export AWS_RAW_CRED=`aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name $ENV_TYPE_ASSUME`
      - export AWS_ACCESS_KEY_ID=$(echo "${AWS_RAW_CRED}" | jq -r '.Credentials.AccessKeyId')
      - export AWS_SECRET_ACCESS_KEY=$(echo "${AWS_RAW_CRED}" | jq -r '.Credentials.SecretAccessKey')
      - export AWS_SESSION_TOKEN=$(echo "${AWS_RAW_CRED}" | jq -r '.Credentials.SessionToken')
  build:
    commands:
      - cd "$CODEBUILD_SRC_DIR"
      - ls -al
      - terraform --version
      #- cd "environments/$TF_ENV/"
      # - terraform init -no-color
      # - terraform $TF_ACTION -no-color
      - aws sts get-caller-identity
  post_build:
    commands:
      - echo "terraform $TF_ACTION completed on `date`"
